### ISSUE TITLE
[Not Issue]  Add resolver to readme file

### ISSUE THREAD

**Issue by nandotorterolo** [earldouglas/sbt-heroku-deploy#10]
Add the resolver of plugin in readme file would be great.

resolvers += Resolver.url("earldouglas", new URL("https://dl.bintray.com/earldouglas/sbt-plugins/"))(Resolver.ivyStylePatterns)  

Thanks for your work.

**Comment by earldouglas** [comment]
sbt-heroku-deploy is [linked in the community sbt plugins repository][1], so there's no need to manually add a resolver as above to your project's configuration.  Check out [this example][2] for everything you need to get started.

[1]: https://bintray.com/sbt/sbt-plugin-releases?filterByPkgName=sbt-heroku-deploy
[2]: https://github.com/earldouglas/sbt-heroku-deploy/tree/master/example

**Comment by nandotorterolo** [comment]
Thank you for your time in answering and for working on this projects, I appreciate your explanation, regards
